
set(BUILD_SHARED_LIBS OFF)
set(SKIP_INSTALL_LIBRARIES ON)
set(SKIP_INSTALL_ALL ON)
set(SKIP_INSTALL_HEADERS ON)
set(SKIP_INSTALL_FILES ON)

set(CXMF_FETCH_CONTENTS)

set(ZLIB_LIBRARIES "zlibstatic" CACHE STRING "" FORCE)
set(ZLIB_BUILD_EXAMPLES OFF)

FetchContent_Declare(
	zlib
	GIT_REPOSITORY	https://github.com/madler/zlib.git
	GIT_TAG			51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf # 1.3.1
	OVERRIDE_FIND_PACKAGE
)
list(APPEND CXMF_FETCH_CONTENTS zlib)

if(CXMF_INCLUDE_IMPORTER)
	set(ASSIMP_BUILD_M3D_IMPORTER OFF)
	set(ASSIMP_BUILD_M3D_EXPORTER OFF)
	set(ASSIMP_BUILD_USD_IMPORTER OFF)
	set(ASSIMP_BUILD_USD_VERBOSE_LOGS OFF)
	set(ASSIMP_BUILD_VRML_IMPORTER OFF)
	set(ASSIMP_BUILD_USE_CCACHE ON)
	set(ASSIMP_HUNTER_ENABLED OFF)
	set(ASSIMP_BUILD_FRAMEWORK OFF)
	set(ASSIMP_DOUBLE_PRECISION OFF)
	set(ASSIMP_OPT_BUILD_PACKAGES OFF)
	set(ASSIMP_ANDROID_JNIIOSYSTEM OFF)
	set(ASSIMP_NO_EXPORT ON)
	set(ASSIMP_BUILD_ASSIMP_TOOLS OFF)
	set(ASSIMP_BUILD_SAMPLES OFF)
	set(ASSIMP_BUILD_TESTS OFF)
	set(ASSIMP_COVERALLS OFF)
	set(ASSIMP_INSTALL OFF)
	set(ASSIMP_WARNINGS_AS_ERRORS ON)
	set(ASSIMP_ASAN OFF)
	set(ASSIMP_UBSAN OFF)
	set(ASSIMP_BUILD_DOCS OFF)
	set(ASSIMP_INJECT_DEBUG_POSTFIX ON)
	set(ASSIMP_IGNORE_GIT_HASH ON)
	set(ASSIMP_BUILD_ZLIB OFF)
	set(ASSIMP_INSTALL_PDB OFF)
	set(ASSIMP_BUILD_ASSIMP_VIEW OFF)
	set(ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT OFF)
	set(ASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT OFF)
	set(ASSIMP_BUILD_GLTF_IMPORTER ON)

	set(GLM_BUILD_LIBRARY OFF)
	set(GLM_BUILD_TESTS OFF)
	set(GLM_BUILD_INSTALL OFF)
	set(GLM_ENABLE_CXX_20 ON)

	set(MESHOPT_BUILD_DEMO OFF)
	set(MESHOPT_BUILD_GLTFPACK OFF)
	set(MESHOPT_BUILD_SHARED_LIBS OFF)
	set(MESHOPT_STABLE_EXPORTS OFF)
	set(MESHOPT_WERROR ON)
	set(MESHOPT_INSTALL OFF)

	FetchContent_Declare(
		assimp
		GIT_REPOSITORY	https://github.com/assimp/assimp.git
		GIT_TAG			fb375dd8c0a032106a2122815fb18dffe0283721 # 6.0.2
	)
	FetchContent_Declare(
		glm
		GIT_REPOSITORY	https://github.com/g-truc/glm.git
		GIT_TAG			0af55ccecd98d4e5a8d1fad7de25ba429d60e863 # 1.0.1
	)
	FetchContent_Declare(
		meshoptimizer
		GIT_REPOSITORY	https://github.com/zeux/meshoptimizer.git
		GIT_TAG			6daea4695c48338363b08022d2fb15deaef6ac09 # 0.25
	)
	list(APPEND CXMF_FETCH_CONTENTS assimp glm meshoptimizer)
endif()

FetchContent_MakeAvailable(${CXMF_FETCH_CONTENTS})
